-- =============================================================================
-- Data Proyectos Restante.xlsx → cp_actividades (38 filas).
-- No re-ejecutar si ya importaste este lote (duplica actividades).
-- Ajustes automáticos: si en Excel fecha fin < inicio o medianoche inválida, suma horas o +1 min (chk_cp_act_fechas).
-- Requiere proyectos en cp_proyectos y empleados (María Fernanda, Francisco Perez, Luis Miguel Francia, Jeff Peña…). Ajustá USE si tu BD tiene otro nombre.
-- =============================================================================
-- Importación de actividades → cp_actividades (origen: Data Proyectos Restante.xlsx, hoja «Hoja1»)
-- Requisitos: proyectos ya existentes en cp_proyectos y empleados consultores cargados.
-- Si falta proyecto o empleado, la fila fallará por FK/subconsulta NULL.
-- Filas donde en Excel «fin» < «inicio» (o medianoche huérfana): se corrige automáticamente sumando las horas del registro o +1 min (script).
USE gestor_vacaciones;
SET NAMES utf8mb4;
INSERT INTO cp_actividades (proyecto_id, requerido_por, consultor_asignado_id, descripcion_actividad, prioridad, fecha_hora_inicio, fecha_hora_fin, horas_trabajadas, estado, comentarios, situacion_pago) VALUES
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Análisis de datos del reporte en worskpace antiguo y migrado. Trabajado Nepal Charity.', 'media', '2025-10-14 09:00:00', '2025-10-14 18:00:00', 7.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Reunión. Ajuste de detalles específicos en el análisis de reportes elaborado en Excel, observaciones exactas entre el nuevo reporte y el antiguo reporte de Nepal Charity.', 'media', '2025-10-15 09:59:59', '2025-10-15 15:59:59', 4.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Nepal Charity Análisis Closure', 'media', '2025-10-21 12:30:00', '2025-10-21 12:59:59', 0.50, 'cerrado', 'Reunión, se culminó con VAT Entries.', 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tablero FOPESA en Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Pantallas FOPESA', 'media', '2025-10-21 15:20:00', '2025-10-21 17:00:00', 1.50, 'cerrado', 'Diseño de pantallas para la empresa FOPESA, cambio de idioma', 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tablero Power BI-SENATI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Diseño de Tablero SENATI - Análisis de información e indicadores, división de reporte. Finalización del primer tablero de la categoría "Financiera", en progreso tablero "Académico".', 'alta', '2025-10-29 09:59:59', '2025-10-29 17:00:00', 5.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tablero Power BI-SENATI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Diseño y entrega de Tablero SENATI - Finalización del tablero "Académico" y "Operativo".', 'alta', '2025-10-30 06:59:59', '2025-10-30 12:14:59', 4.75, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tareas de Preventa%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'PROYECTO INTERSAGA Desarrollo del documento “Flujo de Automatización de WhatsApp – Campaña Navideña”, incluyendo definición de objetivos, estructura del flujo conversacional, tono y estilo, recomendaciones y anexos para la automatización del canal.', 'alta', '2025-11-01 12:59:59', '2025-11-01 20:00:59', 3.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tareas de Preventa%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'PROYECTO INTERSAGA Actualización del documento “Flujo de Desarrollo de Automatización de WhatsApp – Campaña Navideña”, incorporando mejoras en los mensajes y estructura conversacional según las oportunidades identificadas en el análisis cognitivo.', 'alta', '2025-11-03 18:24:00', '2025-11-03 19:20:00', 0.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE nombres LIKE '%Francisco%' AND (apellidos LIKE '%Perez%' OR apellidos LIKE '%Pérez%') LIMIT 1), 'Comparación de las versiones de los tableros, anterior y actuales, y cambios de diseño en los tableros actuales segun sea el caso para homologar formatos.', 'alta', '2025-11-04 11:00:00', '2025-11-04 18:00:00', 4.50, 'en_progreso', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE apellidos LIKE '%Francia%' AND nombres LIKE '%Luis%' AND nombres LIKE '%Miguel%' LIMIT 1), 'Analisis de Excel comparativo', 'alta', '2025-10-31 15:00:00', '2025-10-31 18:00:00', 3.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE apellidos LIKE '%Francia%' AND nombres LIKE '%Luis%' AND nombres LIKE '%Miguel%' LIMIT 1), 'Elaboracion de check list para la clasificacion de las diferencias', 'alta', '2025-11-03 09:00:00', '2025-11-03 18:00:00', 9.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE nombres LIKE '%Francisco%' AND (apellidos LIKE '%Perez%' OR apellidos LIKE '%Pérez%') LIMIT 1), 'Comparación de los tableros antiguos versus los nuevos, para validar si las observaciones entran en la categoría de Fabric o diseño en Power Bi.', 'alta', '2025-11-05 09:00:00', '2025-11-05 18:00:00', 8.00, 'en_progreso', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Modificaciones en los reportes de Power BI%' ORDER BY id DESC LIMIT 1), 'juan_pena', (SELECT id FROM empleados WHERE nombres LIKE '%Francisco%' AND (apellidos LIKE '%Perez%' OR apellidos LIKE '%Pérez%') LIMIT 1), 'Comparación de los tableros nuevos versus los anteriores para validar si las diferencias son para solucionarse en Fabric o en Power BI.', 'alta', '2025-11-06 09:00:00', '2025-11-06 12:59:59', 4.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tablero Power BI-SENATI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Correciones provistas por el cliente para la información del tablero realizadas.', 'media', '2025-11-11 12:14:59', '2025-11-11 21:00:00', 3.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tablero FOPESA en Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Francia%' AND nombres LIKE '%Luis%' AND nombres LIKE '%Miguel%' LIMIT 1), 'Desarrollo de pipeline', 'alta', '2025-12-01 08:00:00', '2025-12-01 12:00:00', 3.00, 'en_progreso', 'Avance al 60%', 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tareas de Preventa%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración de documento de Flujo de IA para la Captación y Gestión de Empresas interesadas en vender en EE.UU.', 'alta', '2025-11-21 15:00:00', '2025-11-21 18:00:00', 1.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tareas de Preventa%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Actualización de flujo de Outcome Harvesting para proyecto IA de Practical Action.', 'alta', '2025-12-04 19:05:00', '2025-12-04 20:16:00', 0.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%CELEPSA - Bolsa Horas Soporte Base Maestra RRHH 2025-26%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%Jeff%' OR nombres LIKE '%Jefferson%') AND (apellidos LIKE '%Peña%' OR apellidos LIKE '%Pena%') LIMIT 1), 'Actualización de inicio de sesión Tenant Azure', 'alta', '2025-10-30 06:59:59', '2025-10-30 18:59:59', 6.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tablero Power BI-SENATI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Conversión de íconos de Tablero de Power BI - SENATI de formato a .PNG a requerimiento.', 'media', '2026-01-30 17:00:00', '2026-01-30 18:00:00', 1.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%POWER BI - PRIMA AFP%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Diseño del tablero para Prima AFP en Power BI, elaboración de la visual, estructura de secciones y organización de indicadores para el dashboard de los dos tableros.', 'media', '2026-02-13 12:56:59', '2026-02-13 18:00:00', 2.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%POWER BI - PRIMA AFP%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Corrección de Tablero Prima AFP. Cambios en ambas pestañas .', 'media', '2026-02-19 01:08:00', '2026-02-19 01:53:00', 0.75, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%POWER BI - PRIMA AFP%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Corrección Final Prima AFP. Agregar botón para modificarlo como panel y no ver ambos gráficos al mismo tiempo. Organización de elementos en ambas pantallas.', 'media', '2026-02-23 01:15:59', '2026-02-23 01:23:47', 0.13, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Creación del cronograma de desarrollo de interfaces del proyecto TalentHub.', 'media', '2026-02-01 01:18:59', '2026-02-01 01:54:59', 0.60, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Revisión y creación de componentes de interfaz para el proyecto.', 'media', '2026-01-26 01:25:00', '2026-01-27 00:00:00', 2.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración del diseño de la pantalla de login y estructuración del flujo del sistema', 'media', '2026-01-28 15:27:00', '2026-01-28 20:00:00', 3.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración de la interfaz de dashboard y organización de indicadores.', 'media', '2026-01-29 09:29:00', '2026-01-30 18:00:00', 2.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Diseño de vista detallada de perfiles en el sistema.', 'media', '2026-02-02 01:37:00', '2026-02-02 01:58:00', 0.35, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Diseño de vista de convocatorias y listado.', 'media', '2026-02-03 01:38:59', '2026-02-04 00:00:00', 2.75, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración de vista de gestión de postulantes.', 'media', '2026-02-05 01:41:59', '2026-02-05 10:41:59', 0.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración de la interfaz de colaboradores.', 'media', '2026-02-09 01:49:00', '2026-02-09 03:34:00', 1.75, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración de la pantallad capacitación / aprendizaje, visual', 'media', '2026-02-10 01:50:00', '2026-02-10 02:20:00', 0.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración de la interfaz de proyectos visual', 'media', '2026-02-11 01:53:00', '2026-02-11 02:23:00', 0.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración visual de la vista de analíticas.', 'media', '2026-02-12 09:53:59', '2026-02-12 10:23:59', 0.50, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Tareas de Preventa%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Elaboración de cronograma de desarrollo de interfaces de "Automatización de Indicadores​ de Control - MPF​"', 'alta', '2026-02-26 01:56:00', '2026-02-26 02:41:00', 0.75, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%CELEPSA - Bolsa Horas Soporte CMD 2025-26%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%Jeff%' OR nombres LIKE '%Jefferson%') AND (apellidos LIKE '%Peña%' OR apellidos LIKE '%Pena%') LIMIT 1), 'Restablecimiento de servicio, monitoreo y presentación de informe', 'alta', '2026-02-09 00:00:00', '2026-03-16 00:59:59', 12.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%SOPORTE TECNICO DESARROLLOS 2026%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%Jeff%' OR nombres LIKE '%Jefferson%') AND (apellidos LIKE '%Peña%' OR apellidos LIKE '%Pena%') LIMIT 1), 'AULAS Y HORARIOS: Cambios en el tipo de acceso para los docentes.', 'alta', '2026-01-09 00:00:00', '2026-01-12 00:00:00', 32.00, 'cerrado', 'Proyecto: AULAS Y HORARIOS', 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%SOPORTE TECNICO DESARROLLOS 2026%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%Jeff%' OR nombres LIKE '%Jefferson%') AND (apellidos LIKE '%Peña%' OR apellidos LIKE '%Pena%') LIMIT 1), 'AULAS Y HORARIOS: Forzar cierre de sesión de Office 365', 'alta', '2026-01-12 00:00:00', '2026-01-12 00:00:00', 3.00, 'cerrado', 'Proyecto: Aulas y Horarios', 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%TALENT HUB%' ORDER BY id DESC LIMIT 1), 'magali_sevillano', (SELECT id FROM empleados WHERE (nombres LIKE '%María%' AND apellidos LIKE '%Fernanda%') OR (nombres LIKE '%Maria%' AND apellidos LIKE '%Fernanda%') OR CONCAT(TRIM(nombres),' ',TRIM(apellidos)) LIKE '%María Fernanda%' LIMIT 1), 'Subida de CV de trabajadores a proyecto, modificacion de campos / actualizacion de informacion, funcionamiento de proyecto, dashboard, usuarios', 'media', '2026-02-25 02:38:00', '2026-03-26 00:00:00', 3.00, 'cerrado', NULL, 'pendiente');
