-- Importación de actividades → cp_actividades (origen: Migracion 1.xlsx, hoja «Hoja1»)
-- Requisitos: proyectos ya existentes en cp_proyectos y empleados consultores cargados.
-- Si falta proyecto o empleado, la fila fallará por FK/subconsulta NULL.
-- Filas donde en Excel «fin» < «inicio» (o medianoche huérfana): se corrige automáticamente sumando las horas del registro o +1 min (script).
USE gestor_vacaciones;
SET NAMES utf8mb4;
INSERT INTO cp_actividades (proyecto_id, requerido_por, consultor_asignado_id, descripcion_actividad, prioridad, fecha_hora_inicio, fecha_hora_fin, horas_trabajadas, estado, comentarios, situacion_pago) VALUES
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Migración del tablero de Vencimiento Cercano y Reporte ME2L, adaptación de nuevos formatos en Vencimiento Cercano', 'alta', '2025-10-06 09:00:00', '2025-10-06 17:29:59', 7.50, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Implementación de las funcionalidades de los botones filtro, leyenda y resumen en el tablero de Vencimiento Cercano y continuación de migración del tablero ME2L.', 'media', '2025-10-07 08:29:59', '2025-10-07 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Finalización con la migración del tablero ME2L con estructura de datos según el reporte de Strategy.', 'media', '2025-10-09 08:29:59', '2025-10-10 15:30:00', 5.00, 'cerrado', 'Por parte del cliente falta esclarecer un campo dentro de la base Oracle que ellos manejan, el informe se adapto lo máximo posible, esto se le comunico a Ricardo y al cliente con días de antelación.', 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Levantamiento de observaciones y mejores en el reporte de Vencimiento Cercano y aplicación de estas también en el reporte de ME2L', 'alta', '2025-10-10 14:00:00', '2025-10-10 17:00:00', 3.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de formato del reporte 1 y 2 coordinado con Ricardo. Levantamiento de observaciones y alineamiento con lo solicitado por el cliente', 'alta', '2025-10-13 08:29:59', '2025-10-13 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Inicio de Tablero Demanda, cruce de tablas y armado de graficos', 'alta', '2025-10-14 09:00:00', '2025-10-14 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Inicio del reporte Demanda: validación relacionales de las tablas de la base de datos, armado de graficos.', 'alta', '2025-10-15 09:00:00', '2025-10-15 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de graficos, validación de datos comparando con el reporte de Microstrategy y comienzo de formato visual.', 'alta', '2025-10-16 08:29:59', '2025-10-16 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de formatos visuales y validación de datos.', 'media', '2025-10-17 14:00:00', '2025-10-17 17:00:00', 3.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Inicio de construcción de Tablero BackOrder', 'alta', '2025-10-20 08:29:59', '2025-10-21 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Levantamiento de observaciones de los primeros dos reportes.', 'alta', '2025-10-21 11:29:59', '2025-10-21 17:29:59', 6.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Avance mapeo y armado de graficos - tablas del reporte BackOrder', 'alta', '2025-10-22 08:29:59', '2025-10-22 17:29:59', 8.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Aplicar mejoras y correcciones de los tableros 1 y 2 referentes a formatos y muestra de campos. Avance de reporte BackOrder a un 50%', 'alta', '2025-10-23 08:29:59', '2025-10-23 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Levantamiento de observaciones reporte 1 y 2, avance de las observaciones del reporte 3 validando con el reporte de Microstrategy.', 'alta', '2025-10-24 09:00:00', '2025-10-24 15:00:00', 6.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de correciones del reporte Demanda y avance del reporte BackOrder.', 'alta', '2025-10-27 08:29:59', '2025-10-27 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Avance tablero de logística', 'alta', '2025-10-28 08:29:59', '2025-10-28 12:30:00', 4.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Avance tablero de logística', 'alta', '2025-10-29 08:29:59', '2025-10-29 12:30:00', 4.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de diseño reportes Ventas Logistica', 'alta', '2025-11-03 08:29:59', '2025-11-03 17:29:59', 8.00, 'cerrado', NULL, 'pendiente'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Revisión de relaciones entre tablas del reporte Backorder y validación de datos.', 'alta', '2025-11-04 08:29:59', '2025-11-04 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Avance pagina 1 y 2 del reporte BackOrder con datos validados, correción de relaciones para pagina 3.', 'alta', '2025-11-05 08:29:59', '2025-11-06 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de armado del reporte BackOrder y ajuste a nivel de diseño del reporte Niveles de Inventario', 'alta', '2025-11-06 08:29:59', '2025-11-06 15:30:00', 6.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Aplicación de las observaciones del reporte ME2L y avance de las observaciones de Demanda.', 'alta', '2025-11-07 14:29:59', '2025-11-07 17:29:59', 3.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Avance de observaciones tablero demanda', 'alta', '2025-11-10 09:00:00', '2025-11-10 12:59:59', 4.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Avance al 80% de las observaciones del reporte Nivel de Inventario.', 'alta', '2025-11-11 08:29:59', '2025-11-11 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Finalización de las observaciones reporte Niveles de Inventario y avance de las correspondientes a BackOrder', 'alta', '2025-11-12 09:00:00', '2025-11-12 17:00:00', 7.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Ajuste en el reporte Niveles de Inventario y avance en los de BackOrder', 'media', '2025-11-14 14:00:00', '2025-11-14 17:29:59', 3.50, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Modificación de conexiones entre tablas y verificación manual con los reportes de Microstrategy.', 'alta', '2025-11-17 09:00:00', '2025-11-17 12:59:59', 4.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de levantamiento de todas las observaciones con validación de datos cruzando con Microstrategy.', 'alta', '2025-11-18 09:00:00', '2025-11-18 09:59:59', 1.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Revisión y corrección integral del reporte: ajustes en el modelo de datos, configuración de relaciones e interacciones, corrección de medidas (US$, UU, BackOrder), ajustes en filtros cruzados (tipo de cambio), adecuación del comportamiento de motivos de no atención y actualización final de visuales según las observaciones enviadas.', 'alta', '2025-11-20 11:00:00', '2025-11-20 15:30:00', 4.50, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Cambios en las formulas DAX, modificación gráfico Retraso del proveedor vs Productos no atendidos y Sku no atendidas', 'alta', '2025-11-24 09:00:00', '2025-11-24 12:59:59', 4.00, 'cerrado', NULL, 'pagado');
