-- Importación desde Control de Horas.xlsx → cp_actividades
-- IMPORTANTE: solo las primeras 5 filas del Excel (p. ej. captura proyecto Migración MSTR). Para todo el libro: ejecutar sin --solo.
-- Requisitos: proyectos ya existentes en cp_proyectos y empleados consultores cargados.
-- Si falta proyecto o empleado, la fila fallará por FK/subconsulta NULL.
-- Filas donde en Excel «fin» < «inicio» (o medianoche huérfana): se corrige automáticamente sumando las horas del registro o +1 min (script).
USE gestor_vacaciones;
SET NAMES utf8mb4;
INSERT INTO cp_actividades (proyecto_id, requerido_por, consultor_asignado_id, descripcion_actividad, prioridad, fecha_hora_inicio, fecha_hora_fin, horas_trabajadas, estado, comentarios, situacion_pago) VALUES
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Migración del tablero de Vencimiento Cercano y Reporte ME2L, adaptación de nuevos formatos en Vencimiento Cercano', 'alta', '2025-10-06 09:00:00', '2025-10-06 17:29:59', 7.50, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Implementación de las funcionalidades de los botones filtro, leyenda y resumen en el tablero de Vencimiento Cercano y continuación de migración del tablero ME2L.', 'media', '2025-10-07 08:29:59', '2025-10-07 17:29:59', 8.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Finalización con la migración del tablero ME2L con estructura de datos según el reporte de Strategy.', 'media', '2025-10-09 08:29:59', '2025-10-10 15:30:00', 5.00, 'cerrado', 'Por parte del cliente falta esclarecer un campo dentro de la base Oracle que ellos manejan, el informe se adapto lo máximo posible, esto se le comunico a Ricardo y al cliente con días de antelación.', 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'ricardo_martinez', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Levantamiento de observaciones y mejoras en el reporte de Vencimiento Cercano y aplicación de estas también en el reporte de ME2L', 'alta', '2025-10-10 14:00:00', '2025-10-10 17:00:00', 3.00, 'cerrado', NULL, 'pagado'),
((SELECT id FROM cp_proyectos WHERE proyecto LIKE '%Migración de tableros de control de MSTR a Power BI%' ORDER BY id DESC LIMIT 1), 'rodrigo_loayza', (SELECT id FROM empleados WHERE apellidos LIKE '%Valdivia%' AND (nombres LIKE '%Nicolas%' OR nombres LIKE '%Nicolás%') LIMIT 1), 'Termino de formato del reporte 1 y 2 coordinado con Ricardo. Levantamiento de observaciones y alineamiento con lo solicitado por el cliente', 'alta', '2025-10-13 08:29:59', '2025-10-13 17:29:59', 8.00, 'cerrado', NULL, 'pagado');
